# Generated by Django 5.1.2 on 2024-10-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_qualification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qualification',
            new_name='Admin',
        ),
    ]
